lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "bbswm"

[packages.directory]
path = "."

[[packages]]
name = "bidict"
version = "0.23.1"

[[packages.wheels]]
name = "bidict-0.23.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/99/37/e8730c3587a65eb5645d4aba2d27aae48e8003614d6aaf15dda67f702f1f/bidict-0.23.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "5dae8d4d79b552a71cbabc7deb25dfe8ce710b17ff41711e13010ead2abfc3e5"

[[packages]]
name = "certifi"
version = "2026.1.4"

[[packages.wheels]]
name = "certifi-2026.1.4-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e6/ad/3cc14f097111b4de0040c83a525973216457bbeeb63739ef1ed275c1c021/certifi-2026.1.4-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9943707519e4add1115f44c2bc244f782c0249876bf51b6599fee1ffbedd685c"

[[packages]]
name = "charset-normalizer"
version = "3.4.4"

[[packages.wheels]]
name = "charset_normalizer-3.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
url = "https://files.pythonhosted.org/packages/c0/10/d20b513afe03acc89ec33948320a5544d31f21b05368436d580dec4e234d/charset_normalizer-3.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"

[packages.wheels.hashes]
sha256 = "11d694519d7f29d6cd09f6ac70028dba10f92f6cdd059096db198c283794ac86"

[[packages]]
name = "dbus-fast"
version = "4.0.0"

[[packages.wheels]]
name = "dbus_fast-4.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"
url = "https://files.pythonhosted.org/packages/6f/df/584e55aa3afa108c3dc34a7a307bfbb628954ad0a393a3a3dc8e76315724/dbus_fast-4.0.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl"

[packages.wheels.hashes]
sha256 = "aa367aaad3a868dfb9373eca8868a2a0810bac6cbe35b67460682127834c2460"

[[packages]]
name = "desktop-notifier"
version = "6.2.0"

[[packages.wheels]]
name = "desktop_notifier-6.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/91/36/b32a806dbb7bce308fecc977220c03ca7990831491bebc582b02619ff980/desktop_notifier-6.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "193b0885e694a99ae22f72234c91afbac633074295b44183bf9716dd4077b8f3"

[[packages]]
name = "exaroton"
version = "0.0.7"

[[packages.wheels]]
name = "exaroton-0.0.7-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/97/72/586d7caa7fbbe0d9bfd3804f8df4a182b755f0f1351c50770a3157690911/exaroton-0.0.7-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "5ee85a5281521059981c0da7cdab6afd4e9c7ee953cdede17ae07b85b3d4453e"

[[packages]]
name = "idna"
version = "3.11"

[[packages.wheels]]
name = "idna-3.11-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0e/61/66938bbb5fc52dbdf84594873d5b51fb1f7c7794e9c0f5bd885f30bc507b/idna-3.11-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "771a87f49d9defaf64091e6e6fe9c18d4833f140bd19464795bc32d966ca37ea"

[[packages]]
name = "packaging"
version = "26.0"

[[packages.wheels]]
name = "packaging-26.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b7/b9/c538f279a4e237a006a2c98387d081e9eb060d203d8ed34467cc0f0b9b53/packaging-26.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b36f1fef9334a5588b4166f8bcd26a14e521f2b55e6b9de3aaa80d3ff7a37529"

[[packages]]
name = "requests"
version = "2.32.5"

[[packages.wheels]]
name = "requests-2.32.5-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "2462f94637a34fd532264295e186976db0f5d453d1cdd31473c85a6a161affb6"

[[packages]]
name = "tk"
version = "0.1.0"

[[packages.wheels]]
name = "tk-0.1.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/1e/0b/029cbdb868bb555fed99bf6540fff072d500b3f895873709f25084e85e33/tk-0.1.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "703a69ff0d5ba2bd2f7440582ad10160e4a6561595d33457dc6caa79b9bf4930"

[[packages]]
name = "tkthread"
version = "0.5.2"

[[packages.wheels]]
name = "tkthread-0.5.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/14/16/10494f1e2ffaf9487f919633f05749e3ccd0113e731c518de7f903e791ed/tkthread-0.5.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "fcf52989c09bee8150cb86ce566b0c8dcbc5627c4ff1a326e1c4c0d1fd02967d"

[[packages]]
name = "typing-extensions"
version = "4.15.0"

[[packages.wheels]]
name = "typing_extensions-4.15.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f0fa19c6845758ab08074a0cfa8b7aecb71c999ca73d62883bc25cc018c4e548"

[[packages]]
name = "urllib3"
version = "2.6.3"

[[packages.wheels]]
name = "urllib3-2.6.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/39/08/aaaad47bc4e9dc8c725e68f9d04865dbcb2052843ff09c97b08904852d84/urllib3-2.6.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bf272323e553dfb2e87d9bfd225ca7b0f467b919d7bbd355436d3fd37cb0acd4"
